name: flutter_translation_sheet
description: Flutter Translation Sheet (fts) is a simple tool to help you with
  localization (l10n), using automatic GoogleSheet translations via Google
  Translate, generating json, arb and dart files.
version: 1.0.23
maintainer: Rodrigo López (@roipeker)
homepage: https://github.com/roipeker/flutter_translation_sheet
repository: https://github.com/roipeker/flutter_translation_sheet/
issue_tracker: https://github.com/roipeker/flutter_translation_sheet/issues

executables:
  fts: main

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  args:
  collection:
  dcli:
  googleapis:
  googleapis_auth:
  http:
  io:
  path:
  recase:
  watcher:
  yaml:

dev_dependencies:
  pedantic: ^1.11.1
