name: flutter_translation_sheet
description: Flutter Translation Sheet (fts) is a simple tool to help you with
  localization (l10n), using automatic GoogleSheet translations via Google
  Translate, generating json, arb and dart files.
version: 1.0.26
maintainer: Rodrigo López (@roipeker)
homepage: https://github.com/roipeker/flutter_translation_sheet
repository: https://github.com/roipeker/flutter_translation_sheet/
issue_tracker: https://github.com/roipeker/flutter_translation_sheet/issues

executables:
  fts: main

environment:
  sdk: ">=2.18.2 <3.0.0"

dependencies:
  args: ^2.3.1
  collection: ^1.16.0
  dcli: ^1.35.2
  googleapis: ^9.2.0
  googleapis_auth: ^1.3.1
  http: ^0.13.5
  io: ^1.0.3
  path: ^1.8.2
  recase: ^4.1.0
  watcher: ^1.0.2
  yaml: ^3.1.1

dev_dependencies:
  lints: ^2.0.1
