name: flutter_translation_sheet
description: Flutter Translation Sheet (fts) is a simple tool to help you with
  localization (l10n), using automatic GoogleSheet translations via
  (GTranslate), generating json, arb and dart files.
version: 1.0.21
homepage: https://github.com/roipeker/flutter_translation_sheet

executables:
  fts: main

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  args: ^2.3.1
  collection: ^1.16.0
  dcli: ^1.31.2
  googleapis: ^9.1.0
  googleapis_auth: ^1.3.1
  http: ^0.13.4
  io: ^1.0.3
  path: ^1.8.2
  recase: ^4.0.0
  watcher: ^1.0.1
  yaml: ^3.1.1

dev_dependencies:
  pedantic: ^1.11.1
