name: flutter_translation_sheet
description: Flutter Translation Sheet Generator is a simple tool to help you with localization (l10n), using automatic GoogleSheet translations (via GTranslate), generating json & dart files.
version: 1.0.12+22
homepage: https://github.com/roipeker/flutter_translation_sheet

executables:
  fts: main

environment:
  sdk: ">=2.13.0 <3.0.0"

dependencies:
  dcli: ^1.7.1
  recase: ^4.0.0
  args: ^2.2.0
  http: ^0.13.3
  googleapis: ^4.0.0
  googleapis_auth: ^1.1.0
  yaml: ^3.1.0
  collection: ^1.15.0
  io: ^1.0.0
  path: ^1.8.0

dev_dependencies:
  pedantic: ^1.11.1
