name: translate_cli
description: A super simple l10n tool with auto translations via GoogleSheet and generation of json and dart files.
version: 1.0.4

executables:
  translate_cli:

environment:
  sdk: ">=2.13.0 <3.0.0"

dependencies:
  dcli: ^1.7.1
  recase: ^4.0.0
  args: any
  csv: ^5.0.0
  http: ^0.13.3
  googleapis: ^4.0.0
  googleapis_auth: ^1.1.0
  yaml: ^3.1.0

dev_dependencies:
  pedantic: ^1.11.1
